[video]
src_type = "opencv"
#source = "rtsp://dispatch:dispatch@localhost:8554/axis-media/media.amp?camera=1"
source = 0

[command]
default = "record"

[backend]
url = "http://127.0.0.1:50051"

[misc]
log_level = "INFO"
storage_path = "/tmp"